### ISSUE TITLE
Clarification on unit of pdot

### ISSUE THREAD

**Issue by AnthonyLeonardoGracio** [AdaCore/RESSAC_Use_Case#25]
Document: UseCaseDevelopment/Layer1_MMS/RESSAC_muXAV_SystemRQ_MMS_SW_Incr1.doc
Commit: 74aa074

In 4.1.3, it's said that pdot drives the speed of the AV. But in the Guarantees listed in 6.7.3.2, pdot is compared with parameters that have Angle.s-1 for unit.

Is pdot an angular speed then? I initially thought that it was driving the speed of the AV relatively to the ground.

**Comment by ledinot** [comment]
To feel uncomfortable here is legitimate.
pdot  actuaĺly is an angular speed.
Don't try to interpret it, or see it as the propeller shaft speed.
Translational speed of the drone can be computed from pdot plus q and paramters.

Envoyé depuis mon appareil Samsung


-------- Message d'origine --------
De : Anthony Leonardo Gracio <notifications@github.com>
Date : 28/06/2017 15:07 (GMT+01:00)
À : AdaCore/RESSAC_Use_Case <RESSAC_Use_Case@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Message publicitaire : ] [AdaCore/RESSAC_Use_Case] Clarification on unit of pdot (#25)


Document: UseCaseDevelopment/Layer1_MMS/RESSAC_muXAV_SystemRQ_MMS_SW_Incr1.doc
Commit: 74aa074<https://github.com/AdaCore/RESSAC_Use_Case/commit/74aa0748114875dcf20bcdf7928afa69a77abb4b>

In 4.1.3, it's said that pdot drives the speed of the AV. But in the Guarantees listed in 6.7.3.2, pdot is compared with parameters that have Angle.s-1 for unit.

Is pdot an angular speed then? I initially thought that it was driving the speed of the AV relatively to the ground.

**Comment by AnthonyLeonardoGracio** [comment]
Ok, thanks for the answer. I am closing the issue then.
